### PR TITLE
Issue #515

### PR DESCRIPTION
**Pull request by rimjhimittal**
solved https://github.com/ModECI/MDF/issues/515#issue-2189616553

### CODE REVIEW

**Comment by pgleeson** [comment]
@rimjhimittal It's good practice to open PRs just to fix one issue at a time. There are changes in here too for the fix related to onnx.py, so best take these out.
Also make sure your code is `black` formatted before you commit, see https://mdf.readthedocs.io/en/latest/api/Contributing.html#step-7

**Comment by pgleeson** [comment]
Also make sure you pull in the latest changes from the main mdf `development` branch, as there have been a few changes there in the past few days.

**Comment by rimjhimittal** [comment]
@pgleeson Alright Padraig, Thanks. I'll take care of that from now on.

**Comment by pgleeson** [comment]
Thanks @rimjhimittal!

**Pull request merged**
