### PR TITLE
Include Outreachy-Modeci Contributions on MDF

### PR DESCRIPTION
**Pull request by Onoyiza**
This pull request adds the tasks given for the OutreachyContribution Phase with ModECI. I have created a folder called outreachy-modeci-contributions that contain folders for each task given. I have added a README.md for each task that outlines the steps required to complete the task. Each task folder contains the resulting files (txt, json, yaml, ipynb.....) gotten from working on the task.

I would appreciate any feedback regarding this pull request. This pull request is a follow-up to my previous [pull request](https://github.com/ModECI/MDF/pull/429).

### CODE REVIEW

**Comment by Onoyiza** [comment]
Hi @pgleeson, 

I have created this new pull request. 
Thank you for your feedback on my previous [pull request](https://github.com/ModECI/MDF/pull/429).
I have created a notebook that converts keras model to mdf. I used the [keras2mdf](https://github.com/ModECI/MDF/blob/main/examples/TensorFlow/Keras/keras2mdf.py) helper function but made a small change to it. I updated the condition on _relu_ for the **create_activation_node** function. 
I made the change because the previous code implemented True(equivalent to 1) when the input values are positive rather than the value itself. 
I noticed it when I evaluated the mdf model and got a different prediction from the keras model. This led me to look for the root cause. 
I am working on the pytorch_to_mdf model.

I look forward to your feedback. Thank you.

**Comment by pgleeson** [comment]
Hi @Onoyiza. Thanks for athe update. This all looks great!
One final thing though, could you update the file https://github.com/ModECI/MDF/blob/main/examples/TensorFlow/Keras/keras2mdf.py and use that in your notebook (e.g. adding '../../../../examples/TensorFlow/Keras' to the path with sys.path.append), and update/fix that file, ensuring the example in https://github.com/ModECI/MDF/tree/main/examples/TensorFlow/Keras still works?

**Comment by Onoyiza** [comment]
Hi @pgleeson. Thanks for your feedback!

I will do that now and revert back.

Thank you.

**Comment by Onoyiza** [comment]
Hi @pgleeson,

I have updated the [keras2mdf](https://github.com/ModECI/MDF/blob/main/examples/TensorFlow/Keras/keras2mdf.py) in the Keras folder in examples and added the path in my notebook and it still works. I also ran the example in [https://github.com/ModECI/MDF/tree/main/examples/TensorFlow/Keras](https://github.com/ModECI/MDF/tree/main/examples/TensorFlow/Keras ). 

Is there any other task I should be working on? 

I look forward to your response. Thank you.

**Comment by Onoyiza** [comment]
Hi @pgleeson. 

Thanks for your feedback!

**Comment by pgleeson** [comment]
Closing all previous Outreachy application period pull requests.

**Pull request closed without merging**
