### PR TITLE
Adds Installation/Quick Start pages to documentation

### PR DESCRIPTION
**Pull request by sakshikaushik717**
Solves #208

### CODE REVIEW

**Comment by pgleeson** [comment]
Thanks for this @sakshikaushik717. I've changed the target to our development branch as the docs have been updated a bit there.

**Comment by pgleeson** [comment]
Thanks again @sakshikaushik717, I've merged it into development and it will get deployed on the main branch soon (and so get deployed to https://mdf.readthedocs.io/en/latest/).

**Comment by sakshikaushik717** [comment]
Hi @pgleeson , thanks for merging this, can you also point me to some slightly advanced bug now that I have the basic knowledge of the workflow and the contribution guidelines?

**Comment by pgleeson** [comment]
@sakshikaushik717 I'm struggling to find some more entry level bugs/issues in the main code, hence making the 2 suggested tasks here: https://github.com/ModECI/MDF/discussions/213#discussioncomment-2478814. These should be a good way of demonstrating your knowledge of Python/ML and learning some MDF along the way.

**Comment by sakshikaushik717** [comment]
Sure, will work on these tasks. I have already tried out adding new nodes to the graph. I will update and share the public link with you. Thanks!

**Pull request merged**
