### PR TITLE
Remove version caps on package dependencies.

### PR DESCRIPTION
**Pull request by 29riyasaxena**
Hi! I have removed the version caps on package dependencies.  @pgleeson @sanjayankur31

### CODE REVIEW

**Comment by davidt0x** [comment]
Looks like code that invokes torch.onnx.export is failing because example_outputs is no longer a supported arg since 1.11, deprecated since 1.10. Simply removing that argument from the code should remove this error from the code.

**Comment by 29riyasaxena** [comment]
My checks are failing after removing these version caps on package. How to proceed with it @pgleeson @sanjayankur31.

**Comment by pgleeson** [comment]
@29riyasaxena Please look into making the change above that @davidt0x suggests. 

Also you have included changes to the notebook on this PR, please remove them from this one. It's best to open PRs with changes only for specific (ideally one) issue. 
Additionally, don't remove the versioning info for modelspec, neuromllite and pyneuroml. They will require some specific version information, as some older different versions won't work with MDF.

**Comment by kmantel** [comment]
I think the psyneulink minimum should also stay - lower versions will break. No issue with removing caps though

**Comment by pgleeson** [comment]
Closing as version caps have been changed in other branches. Thnaks for your initial work on this @29riyasaxena.

**Pull request closed without merging**
