### PR TITLE
Renaming the Scheduler, Translator implemented and tested

### PR DESCRIPTION
**Pull request by Shanka123**

### CODE REVIEW

**Comment by pgleeson** [comment]
@Shanka123 The development branch was out of date with respect to main. It's been updated now. Can you merge development into this and solve any issues so it will be clearer to see what exactly has changed?

**Comment by pgleeson** [comment]
FYI @Shanka123 I'm looking at merging your updates with some of my recent changes & tidying up in this branch: https://github.com/ModECI/MDF/tree/sp_test_2. When that's ready I'll merge it into development

**Comment by Shanka123** [comment]
> FYI @Shanka123 I'm looking at merging your updates with some of my recent changes & tidying up in this branch: https://github.com/ModECI/MDF/tree/sp_test_2. When that's ready I'll merge it into development

**Comment by Shanka123** [comment]
@pgleeson After discussing with @jdcpni last week, I implemented an extended version of the translator which would not only convert the state to stateful parameters with time derivatives only, but any expression (including time derivative). For example, if there is an expression in the output port, it would be referenced by a function that would evaluate the expression. The same goes for state along with changing the name to stateful parameter and addition of dt as a parameter, and time as a stateful parameter if there is a time derivative associated with it. I will update the issue, push the updated code along with test examples into my branch soon.

**Comment by pgleeson** [comment]
Ok, understood @Shanka123. I've opened a PR for other changes, it would be great if you could have a look at that & merge before adding updates in your branch, it just makes it easier to navigate the new additions.
Quick notes on the existing examples:
- There's a lot of reptition between the run_translated*.py, translator.py, full_translator.py. Just create a function and call it once from each place.
- There's no need for an explicit parameter **time** if there is just a time_derivative expression, the update expression will just be a function of dt not time.
- A README summarising your relevant examples with images/graphs/plots would be very helpful to illustrate what works.

**Review by pgleeson — APPROVED** [review]

**Pull request merged**
