### PR TITLE
added export models supported by MDF

### PR DESCRIPTION
**Pull request by parikshit14**
- changed exporter.py docstring as it wasn't translated properly because it was missing a newline character between the args and the initial statement.
Screenshot from 2022-07-14 11-24-55
- added all export models present in the example folder with their readme respectively.
- Generated the page locally and works fine.

### CODE REVIEW

**Comment by parikshit14** [comment]
updated the **generate.py** to copy the content from the readmes in example folder to **doc/sphinx/source/api/export_format/** folder.

**Comment by pgleeson** [comment]
Looks good @parikshit14, have tested locally. 

I think the best option is to make a subfolder in export_format for each of NeuroML, etc. and copy the md file in **there** instead, and then copy all the individual *.png, *.py, *.json files (e.g. from https://github.com/ModECI/MDF/tree/main/examples/NeuroML) into these. Then at least the links generated from text like: `[ABCD.py](ABCD.py) is a script...` will at least point to a valid file which a be downloaded and images will display properly...

**Comment by parikshit14** [comment]
@pgleeson updates the folder structure as recommended, though some images are still not able to load because they have the syntax in the readmes as 
eg: (NeuroML readme)
`<p align="center"></p>`
this is not able to load but 
`` loads fine

**Comment by pgleeson** [comment]
@parikshit14 Closing this, as the majority of the changes were added with #300, that just has selected images which were added to the docs directory as and when they were used in the readmes. I also updated the readmes to use the version of adding images that sphinx prefers ``. The links to the json files and python files are not working though.

**Pull request closed without merging**
