### PR TITLE
Add contributors

### PR DESCRIPTION
**Pull request by Monsurat-Onabajo**
Creating a documentation for contributors page

### CODE REVIEW

**Comment by pgleeson** [comment]
Thanks @Monsurat-Onabajo. Can you change this to a pull request to the devlopment branch though?

**Comment by Monsurat-Onabajo** [comment]
Ok, i will change it now

**Comment by pgleeson** [comment]
@Monsurat-Onabajo One of the tests associated with this pull request is failing, see https://github.com/ModECI/MDF/actions/runs/3657147584

This is due to the fact that we test the formatting of the files on every commit also. We use a standard format https://github.com/psf/black as this minimises the changes between commits especially when people have different coding styles.

If you install [pre-commit](https://pre-commit.com/) using `pip install pre-commit` and type `pre-commit run --all-files` at the top level MDF directory, this should change all the relevant files ot the correct formatting before you commit, and when you do commit the tests should pass.

**Comment by Monsurat-Onabajo** [comment]
ok, i will definitely take note of that

**Comment by pgleeson** [comment]
Some minor tweaks:
- Don't include the [PsyNeuLink](https://github.com/ModECI/PsyNeuLink) repo as a source of contributors, as that's a fork of PsyNeuLink, and most commits there have nothing to do with ModECI
- Use just:  - [@justinjunge](https://github.com/justinjunge) not: - Name Not Available ([@justinjunge](https://github.com/justinjunge)), e.g.
- github -> GitHub

**Comment by pgleeson** [comment]
Looks good, thanks @Monsurat-Onabajo!

**Pull request merged**
