### PR TITLE
Outreachy/MDF/Contributions

### PR DESCRIPTION
**Pull request by Olawumi-11**
This pull request contains the tasks given for the OutreachyContribution Phase. I have created a folder called Outreachy_contributions that contain folders for each task given. I have added a README.md that gives a short description of what the task entails.

### CODE REVIEW

**Comment by pgleeson** [comment]
Thanks for your contributions @TaofeeqatDev!

**Comment by TaofeeqatDev** [comment]
Thanks @pgleeson

**Comment by pgleeson** [comment]
@TaofeeqatDev Thanks again for your contributions on this. Please don't make any more commits to the branch which is part of this pull request. All applications will be judged based on the state of the code at the application deadline, out of fairness for all applicants.

If you do wish to improve your code, please make a new branch in your own fork and work there.

**Comment by TaofeeqatDev** [comment]
> 

@pgleeson  

> @TaofeeqatDev Thanks again for your contributions on this. Please don't make any more commits to the branch which is part of this pull request. All applications will be judged based on the state of the code at the application deadline, out of fairness for all applicants.
> 
> If you do wish to improve your code, please make a new branch in your own fork and work there.

Thanks for the feedback @pgleeson. I didn't make any changes nor any code improvement to this file. I just went through my repository and I discovered I didn't upload the python script that I use for my keras to MDF notebook and that was the reason I uploaded it. Because my second notebook won't run if I don't upload it. I sincerely apologise for that.

**Pull request closed without merging**
