### PR TITLE
Condition parsing

### PR DESCRIPTION
**Pull request by kmantel**
Solves issues related to nested conditions (needed for conditions like Any, All, Not, etc) when exporting or importing from serialized formats

### CODE REVIEW

**Comment by pgleeson** [comment]
@kmantel Testing this locally it failed with graph_scheduler 1.0.0rc2, but worked with 1.0.0. 

MDF is pinned to graph_scheduler>=0.2.0, <1.0.1 (so it didn't force an update). Any reason we can't use the latest 1.1.1 version?

**Comment by kmantel** [comment]
> @kmantel Testing this locally it failed with graph_scheduler 1.0.0rc2, but worked with 1.0.0.
> 
> MDF is pinned to graph_scheduler>=0.2.0, <1.0.1 (so it didn't force an update). Any reason we can't use the latest 1.1.1 version?

I don't think so. We can remove the upper pin here or bump it up if #239 is a WIP. I'll have to check why it's not working with 1.0.0rc2, wasn't expecting that.

**Comment by kmantel** [comment]
OK, it's related to interface changes in pre v1.0.0 graph-scheduler. If there's any reason you'd like to keep using v1.0.0rc2 I can work on supporting it, otherwise I think just setting the lower bound to v1.0.0 would be best. I won't change the interface again without bumping to v2.0.0.

**Comment by pgleeson** [comment]
Sorry my mistake, should have been a minimum requirement, not a maximum one.

**Pull request merged**
