### PR TITLE
modified readme file for conditions, enhancing code clarity

### PR DESCRIPTION
**Pull request by mqnifestkelvin**
Made several corrections to the condition readme file to enhance code clarity and readability. Made additions to the various conditions and how to generate graphs for all the conditions mentioned.

### CODE REVIEW

**Comment by pgleeson** [comment]
These changes look great @mqnifestkelvin. Can you merge the latest from our development branch into yours before I merge this PR?

**Comment by mqnifestkelvin** [comment]
Hello Sir @pgleeson 
Already merged development into mine and waiting further instructions. 
Thank you.

**Comment by pgleeson** [comment]
Looks good! Thanks @mqnifestkelvin!

**Comment by mqnifestkelvin** [comment]
Thank you.

**Comment by mqnifestkelvin** [comment]
Hello Sir @pgleeson 
Is it okay I make all of my submission in a separate repository outside of ModeCEI/MDF repository.  If it, I've worked on a couple of task and would love to hear your take on what I've done so far sir. [Here](https://github.com/mqnifestkelvin/ModECI_starter_setup) is a link to the repository I've been making my submission so far sir.
Would love to hear your thoughts thank you.

**Comment by pgleeson** [comment]
Thanks @mqnifestkelvin. I've given a quick look at your repo and it looks good so far, but can you instead fork the main MDF repo and add the ModECI_starter_setup contents as a subdirectory of examples and open a pull request? 

This will make it easier for us to track and give feedback to all of the contributors who have made contributions. It is also useful as it mimics the process to be used in the actual project, i.e. interns making changes in forks, opening and managing pull requests/branches, getting tests to pass etc. and will be a good way to assess if applicants can manage these core tasks.

**Pull request merged**
