### PR TITLE
added pytorch and onnx visualization

### PR DESCRIPTION
**Pull request by parikshit14**
added support for pytorch and onnx model visualizations.

1. For ONNX visualization:
     - added netron dependency
     - for now just made changes in simple_pytorch_mdf.py to visualize onnx model with the CLI argument "-graph-onnx". This will open the onnx model in the local host (@pgleeson can you try it out locally let me know your reviews about it).

2. For pytorch visualization:
     - added torchviz dependency
     - made some minor changes to simple_pytorch_mdf.py to support torchviz, hence the json and SVG files got updated.
     - this torchviz graph can be added to the readme file of PyTorch folder and replicated for other examples as well.

### CODE REVIEW

**Comment by pgleeson** [comment]
Thanks @parikshit14. Note that the tests look for and run any *.py file in the examples and so your scripts need to pass there too. Add any dependencies you need in the setup files. 
Also, make sure to remove any intermediate files generated for graphviz.
When you add these images to the readme can you give a brief explanation of how they were generated (in a legend) and how it relates to the source code (the torchviz graph is more detailed than expected). It might be good if you explicitly add the weight and bias in the code so the link is clearer. Also generate the mdf graph in a higher level, so the parameters are shown.

**Comment by parikshit14** [comment]
- I added the dependency in the first commit but then also tests are failing so I suppose the test failures are not related to dependencies, also when I tested it locally there arent any failures other than the `xfail` ones(which are expected I suppose).

- Regarding the pytorch model, @pgleeson Actually PyTorch provide a layer of abstraction on the internal working of `nn.Linear` which applies a linear transformation on the input data [documentation](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html) . If we go for explicit mentioning of weights and bias it will cause an extra header to the PyTorch model and make it denser, since the main focus is the conversion of pytorch to mdf I still think we should stick with this approach.

- Updated the MDF graph to `level=3`. The newer version of **simple_pytorch_to_mdf.png** now seems more similar to the PyTorch graph.

**Comment by parikshit14** [comment]
- Updated the simple_pytorch_to_mdf example with added CLI argument for ONNX and torch graph visualization `-graph-onnx` and `-graph-torch` respectively.
- Updated readme to reflect the same.
- tests passing now.

**Comment by pgleeson** [comment]
Thanks @parikshit14, looks good, will merge.

Probably though we don't want netron and torchviz (or psyneulink or pyneuroml...) as dependencies when anyone installs mdf... So it may be good to revisit this issue: https://github.com/ModECI/MDF/issues/199, so the minimal core libs are installed when you pip install, and others are installed for dev, tests etc...

**Pull request merged**
