### PR TITLE
improve the intro language

### PR DESCRIPTION
**Pull request by abhijeetSaroha**
As you said, just try to tweak the **README.md** file to verify that I am able to fork, make changes and push to a branch in your fork.

### CODE REVIEW

**Comment by abhijeetSaroha** [comment]
sorry, for three same commits, i mistakenly did that.

**Comment by pgleeson** [comment]
Thanks for this @abhijeetSaroha. The upbeat tone in your changes in the Readme (visionary, groundbreaking, etc.) are a bit much for academic software documentation, which tends to stick to the facts about the package. You should change this to just update factual errors or improve clarity etc.

**Comment by abhijeetSaroha** [comment]
As you said @pgleeson , I update the `README.md` and add the detail about my jupyter notrbook in the readme file.

Now, I have to create PR for the development branch?

**Comment by abhijeetSaroha** [comment]
@pgleeson please guide me mam.

**Comment by abhijeetSaroha** [comment]
Hi @pgleeson , just wanted to let you know that I have changed the base branch for this pull request from `main` to `development`. This should ensure that the changes are properly incorporated into the development branch.

**Comment by pgleeson** [comment]
Thanks for this @abhijeetSaroha.
- This PR seems to have all your changes now. If so, please delete your other PR and just work on this branch. Update the title of the PR to reflect this.
- You still haven't addressed my initial comment about the top level README (not the readme in the PyTorch folder)
- Your firstTask example doesn't run. Please remove the parameter with id condition, as this has a > which is causing issues with the graphics generation. 
- Can you add a condition and/or time derivative to this model? See existing examples for tips on how to do this. 
- Nice work on the PyTorch example. Can you try changing the color to solid on the nodes like this: https://github.com/ModECI/MDF/blob/8236ca40f1f83c3a06a2c48411e28f08eb62f911/examples/PyTorch/simple_pytorch_to_mdf.py#L106
- Try also some other graphviz engines to see if it makes the graph clearer: https://graphviz.org/docs/layouts/

**Comment by abhijeetSaroha** [comment]
> Thanks for this @abhijeetSaroha. The upbeat tone in your changes in the Readme (visionary, groundbreaking, etc.) are a bit much for academic software documentation, which tends to stick to the facts about the package. You should change this to just update factual errors or improve clarity etc.

I will change it and commit the changes ASAP, @pgleeson .

**Comment by abhijeetSaroha** [comment]
Heyy @pgleeson ,
* I corrected the main `README.md` file.
* make the firstTask running by removing the parameter with id `condition`.
* add some simple condition to the nodes.
* try other graphviz engine for the pytorch model, but i think with `dot` engine graphs are more better while others are bit messy.
* But there is a problem, I don't know why. It shows that to_graph_image() has no argumenet `solid_color`. I have installed `modeci_mdf-0.4.4` version
Screenshot 2023-03-20 220352

**Comment by pgleeson** [comment]
Thanks @abhijeetSaroha 
- Can you run the 3 node example in your first test, and show some output to illustrate that the conditions are actually being used?
- See https://github.com/ModECI/MDF/blob/development/src/modeci_mdf/mdf.py#L539. Make sure you pull the latest in from development and install after you pull it in to your branch.

**Comment by pgleeson** [comment]
Thanks @abhijeetSaroha, the conditions example looks fine now. 
Please see if you can get the graph generator to use the solid color option or to generate with a better layout.  
Also, can you extend the pytorch example to use multiple images (~100) in the pytorch and mdf networks and work out the % accuracy of guessing the label versus the actual labels?

**Comment by abhijeetSaroha** [comment]
Okk @pgleeson , I will take a look. 👍

**Comment by abhijeetSaroha** [comment]
@pgleeson can you please help me in answering this question. 
`
Please work with your mentor to provide a timeline of the work you plan to accomplish on the project and what tasks you will finish at each step. Make sure take into account any time commitments you have during the Outreachy internship round. If you are still working on your contributions and need more time, you can leave this blank and edit your application later.
`

Please guide me.

**Comment by pgleeson** [comment]
Please see: https://github.com/ModECI/MDF/discussions/398#discussioncomment-5500873

**Comment by pgleeson** [comment]
Closing all previous Outreachy application period pull requests. Thanks again for your interest in this project.

**Pull request closed without merging**
