### PR TITLE
Docs/newer sphinx

### PR DESCRIPTION
**Pull request by Onoyiza**
Hi @pgleeson 

I created this branch from the development branch and I have made two changes. They are:
1. I unpinned the sphinx version
2. I changed the deprecated "InstanceAttributeDocumenter" class to its alternative "AttributeDocumenter" in the conf.py file in docs. 

I used sphinx 6.2.1 to build the documentation. Although the documentation was generated, there were a lot of warnings and errors generated.

### CODE REVIEW

**Comment by pgleeson** [comment]
Thanks @Onoyiza. Can you make a change to the ci.yml (e.g. after https://github.com/ModECI/MDF/blob/main/.github/workflows/ci.yml#L106) so that it will try to build the documentation in all combinations of the supported platforms?

**Comment by Onoyiza** [comment]
> Thanks @Onoyiza. Can you make a change to the ci.yml (e.g. after https://github.com/ModECI/MDF/blob/main/.github/workflows/ci.yml#L106) so that it will try to build the documentation in all combinations of the supported platforms?

Hi @pgleeson. Thank you. I am not sure about how to do it. Can you guide me on how?

**Comment by pgleeson** [comment]
@Onoyiza All of the named steps in that test file will run a short list of commands to check one specific piece of functionality. You need to add a new one which will go in to docs and try to generate the documentation, as you do on your own machine. It will be run on each of the environments listed here: https://github.com/ModECI/MDF/actions/runs/5445216992. Make sure you enable actions on your fork so you can see them running there: https://github.com/Onoyiza/MDF/actions

**Comment by Onoyiza** [comment]
Thank you @pgleeson. I will work accordingly.

**Comment by pgleeson** [comment]
Thanks @Onoyiza!

**Pull request merged**
