### PR TITLE
updated pytorch to MDF model

### PR DESCRIPTION
**Pull request by Anushka-GA**
It is well texted and more improvised version of earlier model.

### CODE REVIEW

**Comment by Anushka-GA** [comment]
hello @pgleeson sir
Thanks for your guidance in pre-commit setup .I was finally able to do it .now I have applied almost all your advices on this model and improvised it. Please let me know your feedback. I faced problem in 2 areas specifically onnx graph was not working due to some reasons.

**Comment by Anushka-GA** [comment]
hello @pgleeson sir,
Thank you so much for your guidance because of which I was able to setup my pre-commit setup and edited the pytorch model.I am still facing some issues in onnx graph part rest all are there.
sir I ran pre-commit as suggested by you . and in my laptop its running without failing but here tests are failing I dont know the reason. looking forward for your feedbacks.
pre-commit

**Comment by pgleeson** [comment]
Thanks @Anushka-GA. You need to make sure that you commit the files after you run pre commit. It will change the formatting of some of the file and this needs to be committed. The first test "Format" should pass after that. Don't worry too much about the rest of the test for now, I think it might be a bigger problem with other libraries.

Can you please consolidate your PRs though, you have 4 open? It might be best to just take the other tasks and put them into this PR. Give the notebooks better names (or put then in clearly named folders), focusing on the task/dataset, not just pytorch_to_mdf.ipynb, etc. Too easy to get confused with existing examples. Also make sure there are no repeated files and no unnecessary files.

**Comment by Anushka-GA** [comment]
hello @pgleeson sir
I will sort all my pull requests and make it look more  better and organised in terms of task and presentation. I  just want to ask one doubt that if i want to submit a document for the tasks done then how should I submit it like in txt format of jupyter or which sort of file.
Thank you.

**Comment by pgleeson** [comment]
@Anushka-GA It's fine if all the contributions for your application are in the same pull request. It's best if you keep the individual tasks in separate folders, and then on the 2-3 contributions you list on your outreachy application, point to the folder in your repo (or to the jupyter notebook if that contains all the work) and give a brief explanation of what you have done for that task in the outreachy application contribution record. Hope this is clear.

**Comment by Anushka-GA** [comment]
hello @pgleeson sir
I will keep your advice in mind. I was considering making two separate folders and storing my contributions in these two folders by tonight's deadline, while removing previous commits to avoid repetition. I only have one question: can we contribute documentation as well? and if so, in what format?
thank you.

**Comment by pgleeson** [comment]
@Anushka-GA I'm not sure what you mean about 'tonight's deadline', the deadline for your application is April 3rd, and you can make changes to your PRs up till then if you like.

You can record multiple contributions for the tasks, just point to the appropriate folder in a branch, but it's much easier for me to test/track/comment on them if they are all in the same branch in one PR.

Not sure what you mean by documentation. If it's documentation for your examples these should be in the notebooks/readmes for the task folders. If it's a change/update to existing mdf documentation, that's fine to record too as a contribution, but in that case it should indeed be in a separate PR (to our development branch) which can be merged, unlike the task examples, which will unlikely all be merged as there are a number of them overlapping in scope.

**Pull request closed without merging**
