### PR TITLE
Outreachy application submission

### PR DESCRIPTION
**Pull request by mqnifestkelvin**
This fork contains all the task submission from task one to task three
I migrated task one and task two from a remote repository created, pls refer to [here](https://github.com/mqnifestkelvin/ModECI_starter_setup) for confirmation the time line of submission of these tasks.
For easy access to all of files please check [here](https://github.com/mqnifestkelvin/MDF/tree/main/Outreachy_application)

### CODE REVIEW

**Comment by pgleeson** [comment]
Thanks for that @mqnifestkelvin. Some comments:
- Re SimpleExample: At least one of the conditions is successfully added, but the example doesn't really make sense - the model will have the same outputs (radius/circumerence..) regardless of how many times it is run. Maybe adjust to show you know how the conditons are being used (e.g. change it to a "wheel" model and one node will be the number of rotations set in a condition and another will be distance travelled)
- I'm having trouble running your keras->mdf notebook. Please update the exponent in your sigmoid function to be more mathematically accurate.

**Comment by mqnifestkelvin** [comment]
Hello @pgleeson thank you for taking time out of your time into looking at my contribution/contributions. 
I will do my best to implement the changes you have mentioned.

Thank you.

**Comment by mqnifestkelvin** [comment]
Hello @pgleeson  I have implemented the issues you pointed out and would be awaiting further directives. 
Thank you.

**Comment by pgleeson** [comment]
Looks good, thanks for your contributions @mqnifestkelvin.

**Comment by mqnifestkelvin** [comment]
Thank you so much for your valuable inputs  and guidance during the period of my contribution @pgleeson

**Comment by pgleeson** [comment]
Closing all previous Outreachy application period pull requests.

**Pull request closed without merging**
