### PR TITLE
All examples passed and requirement.txt is updated with dependencies

### PR DESCRIPTION
**Pull request by PatChizzy**

### CODE REVIEW

**Comment by pgleeson** [comment]
Thanks for this @PatChizzy. Just to clarify, is there any new code here or are you just opening this to show the examples have been run (which is fine)?

**Comment by PatChizzy** [comment]
> Thanks for this @PatChizzy. Just to clarify, is there any new code here or are you just opening this to show the examples have been run (which is fine)?

Hi @pgleeson theres code there as a result of successfully env setup and running SimpleExample.

I just pushed my experiment with the the library here.. 
https://github.com/PatChizzy/MDF/blob/contrib/examples/contribExample.ipynb

**Comment by pgleeson** [comment]
Thanks @PatChizzy. Note the point here though about running pre-commit: https://github.com/ModECI/MDF/blob/development/CONTRIBUTING.md#step-7

**Comment by pgleeson** [comment]
Thanks @PatChizzy, 3 node example looks good! Can you make sure to remove any unnecessary files from this PR, e.g. .vscode, some of abcd.json etc. which are regenerated. Part of the test here is your ability to create clean, concise pull requests which focus on the work you have done which you want to highlight.

**Comment by pgleeson** [comment]
Closing all previous Outreachy application period pull requests. Thanks again for your interest in this project.

**Pull request closed without merging**
