### PR TITLE
outreachy tasks

### PR DESCRIPTION
**Pull request by Anushka-GA**
As part of the first task, I created a three-node structure.

### CODE REVIEW

**Comment by Anushka-GA** [comment]
sure I will do that

**Comment by pgleeson** [comment]
@Anushka-GA If you are opening new pull requests for your contributions, please make sure to close old ones, or if this is still valid, don't forget to make the changes suggested here.

**Comment by Anushka-GA** [comment]
hello @pgleeson sir
sir I was facing some issues in that branch thus I consolidated my work in this branch.
Thank you

**Comment by pgleeson** [comment]
Closing all previous Outreachy application period pull requests. Thanks again for your interest in this project.

**Pull request closed without merging**
