### PR TITLE
Include Outreachy-ModECI Tasks

### PR DESCRIPTION
**Pull request by Onoyiza**
The pull request adds the initial tasks given for the Outreachy Contribution Phase with ModECI. I have added README.md outlining the steps required to complete the task. I have also added requirements.txt files that contain all the installed packages for MDF using different python versions. For versions that I had issues with installing all the dependencies, I have included the error in the requirements.txt files. 

I would appreciate any feedback regarding this pull request. This pull request depends on this [discussion](https://github.com/ModECI/MDF/discussions/398#discussioncomment-5227329)

### CODE REVIEW

**Comment by pgleeson** [comment]
Thanks for this @Onoyiza! Can you pull in the latest changes from our development branch to yours and make this a pull request to our development branch? Also, I've set the GitHub Actions tests to run on this pull request, so make sure the tests are passing.

**Comment by pgleeson** [comment]
@Onoyiza Note also the point here about pre-commit: https://github.com/ModECI/MDF/blob/development/CONTRIBUTING.md#step-7

**Comment by Onoyiza** [comment]
Thanks, @pgleeson! Does this mean that when I fork the repo, I should include all the branches instead of just the main branch? So that I can access the development branch on my own repo.

**Comment by pgleeson** [comment]
@Onoyiza It's not really an issue if you only fork a repo with just main. What you can always do is create a new development branch in your repo (from the main branch) and then merge in changes on development from the source repo to your branch, and then they will be equivalent.

**Comment by Onoyiza** [comment]
Thanks @pgleeson. I didn’t know initially so I deleted my previous fork and created a new fork with all the branches, then I noticed you updated the development branch and I thought about how I could merge  the changes you made in the repos development branch into the branch I created that’s when I learned I could merge files from an upstream repo’s branch into my branch. I will appreciate any additional feedback you have. Thank you.

**Pull request closed without merging**
