### PR TITLE
standard_functions: store python function for each valid mdf function

### PR DESCRIPTION
**Pull request by kmantel**
This would allow psyneulink to directly use these and any other future function added that doesn't have an equivalent implementation in psyneulink, if specified as the type of a function in an MDF file

### CODE REVIEW

**Comment by davidt0x** [comment]
@kmantel @patrickstock 

Looks like this #73 and #71 is failing on 3.9 for linux and macos because somehow tests.test_examples:chdir_back_to_root is missing code I added to set the current directory to sys.path. Should look like this: 
```
 @pytest.fixture(autouse=True)
def chdir_back_to_root(mocker):
    """
    This fixture sets up and tears down state before each example is run. Certain examples
    require that they are run from the local directory in which they reside. This changes
    directory and adds the local directory to sys.path. It reverses this after the test
    finishes.
    """

    # Get the current directory before running the test
    cwd = os.getcwd()
    sys.path.append(".")

    # Some of the scripts do plots. Lets patch matplotlib plot so tests don't hang
    mocker.patch("matplotlib.pyplot.show")
    mocker.patch("matplotlib.pyplot.figure")

    yield

    # We need chdir back to root of the repo
    os.chdir(cwd)
    sys.path.pop()

```

I think it must of gotten clobbered in a merge or something. We need to do this because a couple of Padraig's examples assume local directory is on path. Windows 3.9 is still failing because of PsyNeuLink and winpty.

**Comment by davidt0x** [comment]
Nevermind, that wasn't the issue, I was misreading the stack trace. Not sure what is going on and why it only fails on 3.9. Let me look into this some more.

**Comment by kmantel** [comment]
I've seen this problem intermittently on my local version for some time, while it wasn't showing up on GHA, but I can't replicate it now.

**Comment by kmantel** [comment]
There is still an issue with this code relating to the docs (only built on Travis) - `generate.py` dumps the `mdf_functions` dict to json, but the python functions can't be dumped. They could either be excluded from the file (`MDF_function_specifications.json`) or we could use an alternative like [dill](https://pypi.org/project/dill/) which I've used in psyneulink to handle custom functions in json format.

**Comment by kmantel** [comment]
> There is still an issue with this code relating to the docs (only built on Travis) - `generate.py` dumps the `mdf_functions` dict to json, but the python functions can't be dumped. They could either be excluded from the file (`MDF_function_specifications.json`) or we could use an alternative like [dill](https://pypi.org/project/dill/) which I've used in psyneulink to handle custom functions in json format.

resolved this by excluding from generation

**Pull request merged**
