### PR TITLE
Version update 

### PR DESCRIPTION
**Pull request by Monsurat-Onabajo**

### CODE REVIEW

**Comment by Monsurat-Onabajo** [comment]
hello, i tried merging but it seems i am not authorized to merge it

**Comment by pgleeson** [comment]
> hello, i tried merging but it seems i am not authorized to merge it

@Monsurat-Onabajo Which way did you try merging? This branch into development? It's just us on the core team that have permission to do that for now. And besides, it can't be merged yet, as the tests don't pass on 3.11.

All the relevant changes from development are here as previously requested on the other pull request, so thanks. However, there is one small change here too on the Installation.md file. It's only a minor change but I'm just flagging it to emphasise that for any pull request like this the changes should be the minimum requred for the purpose of the PR.

**Comment by Monsurat-Onabajo** [comment]
Ok, i understand now. I will note the change, thank you

**Comment by pgleeson** [comment]
Mergeing this into a dedicated branch to test latest onnx version.

**Pull request merged**
